#! /bin/bash

echo "Resetting the project..."

echo "Replacing index content..."

echo "
import type { Metadata } from \"next\";
import \"./globals.css\";


export const metadata: Metadata = {
  title: \"Blank Project\",
  description: \"Generated by create blank project\",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang=\"en\">
      <body>
        {children}
      </body>
    </html>
  );
}
" > app/layout.tsx

echo "export default function Home() { 
  return (
    <h1>Hello World!</h1>
  );
}
" > app/page.tsx

echo "Running the project..."
npm run dev