
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Blank Project",
  description: "Generated by create blank project",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="w-full min-h-screen p-4">
        {children}
      </body>
    </html>
  );
}

